# Generated by Django 3.1.4 on 2021-12-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20211211_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
